Repository bhaveshgarg2000/Hacktober-DSA-2022, pull requests merged in 2022-10, with the labels that each got.

#1 stack added
  stack/stack.cpp
Labels: good first issue, hacketoberfest, hacktoberfest-accepted

#3 Created validparenthesis.cpp
  stack/validparenthesis.cpp
Labels: enhancement, hacketoberfest, hacktoberfest-accepted

#4 Validating Balanced expression using stack
  stack/balancedExpression.cpp
Labels: enhancement, good first issue, hacketoberfest, hacktoberfest-accepted

#5 DFS
  DFS/Dfs.class
  DFS/Dfs.java
Labels: good first issue, hacketoberfest, hacktoberfest-accepted

#9 TowerOf Hanoi
  Recursion/tower.cpp
  Recursion/tower.exe
Labels: enhancement, good first issue, hacktoberfest-accepted
